apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-hsqe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-hsqe
    app.kubernetes.io/part-of: test-app-823
  name: retrodep-hsqe
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-hsqe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-hsqe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-823/retrodep-hsqe@sha256:1c2e413b3de0ebfc491a68c5f199f31b1775ba428a8501f726bee86445d1e04f
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
