apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-cgst
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-cgst
    app.kubernetes.io/part-of: test-app-823
  name: pip-e2e-test-cgst
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-cgst
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-cgst
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-823/pip-e2e-test-cgst@sha256:2d90bcc8e0ebdea894cb5fdd38495443eea88442e9634116213d0c599f41d202
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
