apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-gmoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-gmoj
    app.kubernetes.io/part-of: test-app-823
  name: nodejs-no-dockerfile-gmoj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-gmoj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-gmoj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-823/nodejs-no-dockerfile-gmoj@sha256:c6e520438322510c060ff0a02f0ceeee5c06f2ad7be15ab74bca6d2feddf5a30
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
